### ISSUE TITLE
No error in using empty file and then testing default list

### ISSUE THREAD

**Issue by xhdix** [ooni/probe-engine#1123]
**To Reproduce**
1. `$ echo "" > empty.txt`
2. `$ ./miniooni -n --file=empty.txt  dnscheck`

```bash
$ ./miniooni -n --file=emptyfile.txt  dnscheck
[      0.000310] <info> miniooni state directory: /home/username/.miniooni
[      0.000568] <info> miniooni temporary directory: /tmp/ooniengine276239896
[      0.000606] <info> Looking up OONI backends; please be patient...
[      2.436395] <info> session: using probe services: {Address:https://ps2.ooni.io Type:https Front:}
[      2.436422] <info> Looking up your location; please be patient...
[SNIP]
[      5.245644] <info> [1/17] running with input: http://www.jhr.ca/
[      5.246101] <warn> measurement failed: map[error:unsupported URL scheme]
[      5.246115] <info> saving measurement to disk
[      5.246276] <info> [2/17] running with input: http://www.iicwc.org/
[      5.246318] <warn> measurement failed: map[error:unsupported URL scheme]
[      5.246732] <info> saving measurement to disk
[      5.246978] <info> [3/17] running with input: http://www.transparency.org/
[      5.247183] <warn> measurement failed: map[error:unsupported URL scheme]
[      5.247271] <info> saving measurement to disk
[      5.247435] <info> [4/17] running with input: http://www.pgp.com/
[      5.247548] <warn> measurement failed: map[error:unsupported URL scheme]
[      5.247646] <info> saving measurement to disk
[      5.247859] <info> [5/17] running with input: https://www.twitch.tv/
[      8.126280] <info> [100.0%] dnscheck: measure https://151.101.38.167/: unknown_failure: doh: server returned error
[      8.126838] <info> saving measurement to disk
[      8.127326] <info> [6/17] running with input: https://www.sendspace.com/
[     11.472436] <info> [100.0%] dnscheck: measure https://69.31.136.5/: unknown_failure: doh: invalid content-type
[     11.475736] <info> saving measurement to disk
[     11.478436] <info> [7/17] running with input: http://www.talafone.com/
^C
```

**Expected behavior**
```diff
diff --git a/internal/fsx/fsx.go b/internal/fsx/fsx.go
index 6805ed17..2349e9ad 100644
--- a/internal/fsx/fsx.go
+++ b/internal/fsx/fsx.go
@@ -41,6 +41,10 @@ func OpenWithFS(fs FS, pathname string) (File, error) {
                file.Close()
                return nil, fmt.Errorf("input path points to a directory: %w", syscall.EISDIR)
        }
+       if info.Size() == 0 {
+               file.Close()
+               return nil, fmt.Errorf("file is empty")
+       }
        return file, nil
 }

```
And? :thinking:

**Comment by bassosimone** [comment]
This is about to land:

```
% echo "" >empty.txt
% ./miniooni -f empty.txt dnscheck
[      0.002805] <info> Looking up OONI backends; please be patient...
[      1.258055] <info> session: using probe services: {Address:https://ps2.ooni.io Type:https Front:}
[      1.258099] <info> Looking up your location; please be patient...
[      1.427656] <info> - country: IT
[      1.427671] <info> - network: Vodafone Italia S.p.A. (AS30722)
[      1.427686] <info> - resolver's IP: 91.80.36.88
[      1.427699] <info> - resolver's network: Vodafone Italia S.p.A. (AS30722)
[      1.427922] <warn> cannot load inputs: map[error:no input provided]
[      1.428915] <info> sessionresolver: failure rate: primary: 0/2; fallback: 0/0
[      1.429411] <info> whole session: recv   7 kbyte, sent   2 kbyte
2020/12/10 16:16:44 cannot load inputs

% echo $?
1
```

**Comment by bassosimone** [comment]
Fixed in https://github.com/ooni/probe-engine/pull/1132.

**Comment by xhdix** [comment]
I think, when we specify the input, we do not want to do another test. Personally, if I see another test going on, I will stop it.
The problem was that we had a bug in uploading the test list to the remote device. The file was uploaded empty. Because of this, I think the problem still exists in other tests. This is why I suggested a change in `fsx`.

**Comment by bassosimone** [comment]
> [...] The problem was that we had a bug in uploading [... t]he file was uploaded empty.

Thank you, I did not think about this use case! Reopening!

**Comment by bassosimone** [comment]
New behaviour:

```
% ./miniooni -f ./testdata/inputloader1.txt -f ./testdata/inputloader2.txt -f ./testdata/inputloader3.txt run
[      0.001538] <info> Looking up OONI backends; please be patient...
[      0.493896] <info> session: using probe services: {Address:https://ps2.ooni.io Type:https Front:}
[      0.493963] <info> Looking up your location; please be patient...
[      0.852038] <info> - country: IT
[      0.852078] <info> - network: Vodafone Italia S.p.A. (AS30722)
[      0.852089] <info> - resolver's IP: 91.80.36.88
[      0.852102] <info> - resolver's network: Vodafone Italia S.p.A. (AS30722)
[      0.854592] <warn> cannot load inputs: map[error:file did not contain any input: ./testdata/inputloader3.txt]
[      0.856315] <info> sessionresolver: failure rate: primary: 0/3; fallback: 0/0
[      0.856803] <info> whole session: recv   9 kbyte, sent   3 kbyte
2020/12/11 11:42:22 cannot load inputs

% ./miniooni -f ./testdata/inputloader1.txt -f ./testdata/inputloader2.txt -f ./testdata/inputloader3.txt web_connectivity
[      0.001999] <info> Looking up OONI backends; please be patient...
[      0.493603] <info> session: using probe services: {Address:https://ps2.ooni.io Type:https Front:}
[      0.493657] <info> Looking up your location; please be patient...
[      1.016416] <info> - country: IT
[      1.016460] <info> - network: Vodafone Italia S.p.A. (AS30722)
[      1.016477] <info> - resolver's IP: 91.80.36.88
[      1.016490] <info> - resolver's network: Vodafone Italia S.p.A. (AS30722)
[      1.016952] <warn> cannot load inputs: map[error:file did not contain any input: ./testdata/inputloader3.txt]
[      1.018234] <info> sessionresolver: failure rate: primary: 0/2; fallback: 0/0
[      1.018718] <info> whole session: recv   7 kbyte, sent   2 kbyte
2020/12/11 11:42:52 cannot load inputs
```

Will be committed soon.
